<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'auth.login' => 'get1',
  'Sorani\\SimpleFramework\\Auth\\AuthInterface' => 'get2',
  'Sorani\\SimpleFramework\\Auth\\UserInterface' => 'get3',
  'App\\Auth\\ForbiddenMiddleware' => 'get4',
  'subEntry1' => 'get5',
  'twig.extensions' => 'get6',
  'subEntry2' => 'get7',
  'subEntry3' => 'get8',
  'subEntry4' => 'get9',
  'subEntry5' => 'get10',
  'subEntry6' => 'get11',
  'subEntry7' => 'get12',
  'subEntry8' => 'get13',
  'subEntry9' => 'get14',
  'blog.prefix' => 'get15',
  'admin.widgets' => 'get16',
  'subEntry10' => 'get17',
  'admin.prefix' => 'get18',
  'App\\Admin\\Twig\\Extension\\AdminTwigExtension' => 'get19',
  'subEntry11' => 'get20',
  'App\\Admin\\AdminModule' => 'get21',
  'subEntry12' => 'get22',
  'subEntry13' => 'get23',
  'subEntry14' => 'get24',
  'subEntry15' => 'get25',
  'App\\Admin\\Actions\\DashboardAction' => 'get26',
  'subEntry16' => 'get27',
  'subEntry17' => 'get28',
  'env' => 'get29',
  'database.host' => 'get30',
  'database.username' => 'get31',
  'database.password' => 'get32',
  'database.name' => 'get33',
  'views.path' => 'get34',
  'Sorani\\SimpleFramework\\Session\\SessionInterface' => 'get35',
  'Sorani\\SimpleFramework\\Session\\FlashService' => 'get36',
  'subEntry18' => 'get37',
  'Sorani\\SimpleFramework\\Router' => 'get38',
  'Sorani\\SimpleFramework\\Middleware\\CsrfMiddleware' => 'get39',
  'subEntry19' => 'get40',
  'Sorani\\SimpleFramework\\Renderer\\RendererInterface' => 'get41',
  'PDO' => 'get42',
  'App\\Auth\\DatabaseAuth' => 'get43',
  'subEntry20' => 'get44',
  'subEntry21' => 'get45',
  'App\\Auth\\User' => 'get46',
  'Sorani\\SimpleFramework\\Twig\\Extension\\RouterTwigExtension' => 'get47',
  'subEntry22' => 'get48',
  'Sorani\\SimpleFramework\\Twig\\Extension\\PagerFantaExtension' => 'get49',
  'subEntry23' => 'get50',
  'Sorani\\SimpleFramework\\Twig\\Extension\\TextExtension' => 'get51',
  'Sorani\\SimpleFramework\\Twig\\Extension\\TimeExtension' => 'get52',
  'Sorani\\SimpleFramework\\Twig\\Extension\\FlashExtension' => 'get53',
  'subEntry24' => 'get54',
  'Sorani\\SimpleFramework\\Twig\\Extension\\FormExtension' => 'get55',
  'Sorani\\SimpleFramework\\Twig\\Extension\\CsrfExtension' => 'get56',
  'subEntry25' => 'get57',
  'App\\Auth\\Twig\\Extension\\AuthTwigExtension' => 'get58',
  'subEntry26' => 'get59',
  'App\\Blog\\BlogWidget' => 'get60',
  'subEntry27' => 'get61',
  'subEntry28' => 'get62',
  'App\\Auth\\Table\\UserTable' => 'get63',
  'subEntry29' => 'get64',
  'App\\Blog\\Table\\PostTable' => 'get65',
  'subEntry30' => 'get66',
);

    protected function get1()
    {
        return '/login';
    }

    protected function get2()
    {
        return $this->delegateContainer->get('App\\Auth\\DatabaseAuth');
    }

    protected function get3()
    {
        return $this->delegateContainer->get('App\\Auth\\User');
    }

    protected function get5()
    {
        return $this->delegateContainer->get('auth.login');
    }

    protected function get4()
    {
        $object = new App\Auth\ForbiddenMiddleware('loginPath', $this->get5());
        return $object;
    }

    protected function get7()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\RouterTwigExtension');
    }

    protected function get8()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\PagerFantaExtension');
    }

    protected function get9()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\TextExtension');
    }

    protected function get10()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\TimeExtension');
    }

    protected function get11()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\FlashExtension');
    }

    protected function get12()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\FormExtension');
    }

    protected function get13()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Twig\\Extension\\CsrfExtension');
    }

    protected function get14()
    {
        return $this->delegateContainer->get('App\\Auth\\Twig\\Extension\\AuthTwigExtension');
    }

    protected function get6()
    {
        return [
            0 => $this->get7(),
            1 => $this->get8(),
            2 => $this->get9(),
            3 => $this->get10(),
            4 => $this->get11(),
            5 => $this->get12(),
            6 => $this->get13(),
            7 => $this->get14(),
        ];
    }

    protected function get15()
    {
        return '/blog';
    }

    protected function get17()
    {
        return $this->delegateContainer->get('App\\Blog\\BlogWidget');
    }

    protected function get16()
    {
        return [
            0 => $this->get17(),
        ];
    }

    protected function get18()
    {
        return '/admin';
    }

    protected function get20()
    {
        return $this->delegateContainer->get('admin.widgets');
    }

    protected function get19()
    {
        $object = new App\Admin\Twig\Extension\AdminTwigExtension($this->get20());
        return $object;
    }

    protected function get22()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Renderer\\RendererInterface');
    }

    protected function get23()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Router');
    }

    protected function get24()
    {
        return $this->delegateContainer->get('App\\Admin\\Twig\\Extension\\AdminTwigExtension');
    }

    protected function get25()
    {
        return $this->delegateContainer->get('admin.prefix');
    }

    protected function get21()
    {
        $object = new App\Admin\AdminModule($this->get22(), $this->get23(), $this->get24(), $this->get25());
        return $object;
    }

    protected function get27()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Renderer\\RendererInterface');
    }

    protected function get28()
    {
        return $this->delegateContainer->get('admin.widgets');
    }

    protected function get26()
    {
        $object = new App\Admin\Actions\DashboardAction($this->get27(), $this->get28());
        return $object;
    }

    protected function get29()
    {
                $value = $_ENV['ENV'] ?? $_SERVER['ENV'] ?? getenv('ENV');
        if (false !== $value) return $value;
        if (!true) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'ENV' has not been defined");
        }
        return 'production';
    }

    protected function get30()
    {
        return 'localhost';
    }

    protected function get31()
    {
        return 'root';
    }

    protected function get32()
    {
        return 'root';
    }

    protected function get33()
    {
        return 'pratiquepoo';
    }

    protected function get34()
    {
        return 'L:\\Programs\\laragon_full\\www\\Labs\\Grafikart\\my-framework\\resources/views';
    }

    protected function get35()
    {
        $object = new Sorani\SimpleFramework\Session\PHPSession();
        return $object;
    }

    protected function get37()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Session\\SessionInterface');
    }

    protected function get36()
    {
        $object = new Sorani\SimpleFramework\Session\FlashService($this->get37());
        return $object;
    }

    protected function get38()
    {
        return $this->resolveFactory('Sorani\\SimpleFramework\\Router\\RouterFactory', 'Sorani\\SimpleFramework\\Router');
    }

    protected function get40()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Session\\SessionInterface');
    }

    protected function get39()
    {
        $session = $this->get35();
        $object = new Sorani\SimpleFramework\Middleware\CsrfMiddleware($session, 50, '_csrf', 'csrf');
        return $object;
    }

    protected function get41()
    {
        return $this->resolveFactory('Sorani\\SimpleFramework\\Renderer\\TwigRendererFactory', 'Sorani\\SimpleFramework\\Renderer\\RendererInterface');
    }

    protected function get42()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $pdo = new \PDO(
            \sprintf('mysql:host=%s;dbname=%s; charset=utf8mb4', $c->get('database.host'), $c->get('database.name')),
            $c->get('database.username'),
            $c->get('database.password'),
            [
                \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_OBJ,
                \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION
            ]
        );
        if ($pdo->getAttribute(\PDO::ATTR_DRIVER_NAME) === 'mysql') {
            $pdo->setAttribute(\PDO::MYSQL_ATTR_INIT_COMMAND, "SET NAMES 'UTF8'");
        }
        return $pdo;
    }, 'PDO');
    }

    protected function get44()
    {
        return $this->delegateContainer->get('App\\Auth\\Table\\UserTable');
    }

    protected function get45()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Session\\SessionInterface');
    }

    protected function get43()
    {
        $object = new App\Auth\DatabaseAuth($this->get44(), $this->get45());
        return $object;
    }

    protected function get46()
    {
        $object = new App\Auth\User();
        return $object;
    }

    protected function get48()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Router');
    }

    protected function get47()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\RouterTwigExtension($this->get48());
        return $object;
    }

    protected function get50()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Router');
    }

    protected function get49()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\PagerFantaExtension($this->get50());
        return $object;
    }

    protected function get51()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\TextExtension();
        return $object;
    }

    protected function get52()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\TimeExtension();
        return $object;
    }

    protected function get54()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Session\\FlashService');
    }

    protected function get53()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\FlashExtension($this->get54());
        return $object;
    }

    protected function get55()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\FormExtension();
        return $object;
    }

    protected function get57()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Middleware\\CsrfMiddleware');
    }

    protected function get56()
    {
        $object = new Sorani\SimpleFramework\Twig\Extension\CsrfExtension($this->get57());
        return $object;
    }

    protected function get59()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Auth\\AuthInterface');
    }

    protected function get58()
    {
        $object = new App\Auth\Twig\Extension\AuthTwigExtension($this->get59());
        return $object;
    }

    protected function get61()
    {
        return $this->delegateContainer->get('Sorani\\SimpleFramework\\Renderer\\RendererInterface');
    }

    protected function get62()
    {
        return $this->delegateContainer->get('App\\Blog\\Table\\PostTable');
    }

    protected function get60()
    {
        $object = new App\Blog\BlogWidget($this->get61(), $this->get62());
        return $object;
    }

    protected function get64()
    {
        return $this->delegateContainer->get('PDO');
    }

    protected function get63()
    {
        $object = new App\Auth\Table\UserTable($this->get64());
        return $object;
    }

    protected function get66()
    {
        return $this->delegateContainer->get('PDO');
    }

    protected function get65()
    {
        $object = new App\Blog\Table\PostTable($this->get66());
        return $object;
    }

}
